2023-07-06 14:24:44,150 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2023-07-06 14:24:44,153 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application_default']
2023-07-06 14:24:44,160 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application-default', 'login']
2023-07-06 14:24:44,162 DEBUG    root            Running [gcloud.auth.application-default.login] with arguments: []
2023-07-06 14:25:13,667 DEBUG    root            (gcloud.auth.application-default.login) Aborted by user.
Traceback (most recent call last):
  File "/Users/mackayfisher/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mackayfisher/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mackayfisher/google-cloud-sdk/lib/surface/auth/application_default/login.py", line 131, in Run
    command_auth_util.PromptIfADCEnvVarIsSet()
  File "/Users/mackayfisher/google-cloud-sdk/lib/googlecloudsdk/command_lib/auth/auth_util.py", line 130, in PromptIfADCEnvVarIsSet
    console_io.PromptContinue(
  File "/Users/mackayfisher/google-cloud-sdk/lib/googlecloudsdk/core/console/console_io.py", line 305, in PromptContinue
    raise OperationCancelledError(cancel_string)
googlecloudsdk.core.console.console_io.OperationCancelledError: Aborted by user.
2023-07-06 14:25:13,675 ERROR    root            (gcloud.auth.application-default.login) Aborted by user.
